version: '3.9'

services:
  theme:
    image: wielgosz-info/${THEME_SLUG:-wi-sonx-fse}-theme:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/workspaces/${THEME_SLUG:-wi-sonx-fse}
      - node_modules:/workspaces/${THEME_SLUG:-wi-sonx-fse}/node_modules
    restart: always
    environment:
      THEME_NAME: ${THEME_NAME:-'WI Sonx FSE'}
      THEME_SLUG: ${THEME_SLUG:-wi-sonx-fse}
      NODE_ENV: ${NODE_ENV:-development}
      SCRIPT_DEBUG: ${SCRIPT_DEBUG:-true}
      COMPOSER_DISABLE_XDEBUG_WARN: ${COMPOSER_DISABLE_XDEBUG_WARN:-1}
    secrets:
      - user_ssh_key

volumes:
  node_modules: {}

secrets:
  user_ssh_key:
    file: ~/.ssh/id_ed25519
