version: '3.9'

services:
  theme:
    image: wielgosz-info/${THEME_SLUG:-wi-sonx-fse}-theme:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/local/app
      - node_modules:/usr/local/app/node_modules
      - vscode:/root/.vscode-server
    restart: always
    environment:
      THEME_NAME: ${THEME_NAME:-'WI Sonx FSE'}
      THEME_SLUG: ${THEME_SLUG:-wi-sonx-fse}
      NODE_ENV: ${NODE_ENV:-development}
    secrets:
      - user_ssh_key

  composer:
    image: composer:latest
    command: ['/bin/sh', '-c', "while true; do sleep 1000; done"]
    volumes:
      - ./:/app
      - composer_data:/tmp
    profiles:
      - composer

volumes:
  node_modules: {}
  vscode: {}
  composer_data: {}

secrets:
  user_ssh_key:
    file: ~/.ssh/id_rsa
