// WordPress webpack config.
const defaultConfig = require('@wordpress/scripts/config/webpack.config');

// Plugins.
const RemoveEmptyScriptsPlugin = require('webpack-remove-empty-scripts');

// Utilities.
const path = require('path');

// Extract the default config(s) and update the output path.
const configs = Array.isArray(defaultConfig) ? defaultConfig : [defaultConfig];
configs.forEach((config) => {
	config.output.path = path.resolve(process.cwd(), 'build/blocks');
});

// Add theme entrypoints by copying the default scripts config and overwriting entries.
configs.push({
	...configs[0],
	...{
		output: {
			path: path.resolve(process.cwd(), 'build/assets'),
		},
		entry: {
			'editor': path.resolve(
				process.cwd(),
				'assets/scripts',
				'editor.ts'
			),
			'main': path.resolve(
				process.cwd(),
				'assets/scripts',
				'main.ts'
			),
		},
		plugins: [
			// Include (most of) WP's plugin config.
			...configs[0].plugins.filter((plugin) => plugin.constructor.name !== 'CopyPlugin'),

			// Removes the empty `.js` files generated by webpack but
			// sets it after WP has generated its `*.asset.php` file.
			new RemoveEmptyScriptsPlugin({
				stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS,
			}),
		],
	},
});

module.exports = configs;
